name: dart_inversion_of_control
version: 1.0.1
description: A simple library to facilitate inversion of control in dart.
repository: https://github.com/Apolexian/Dartioc

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
